server:
  port: 8080

spring:
  application:
    name: identity-service
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:services/identity-service/.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
