name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check whitespace errors
        run: git diff --check HEAD^ HEAD || git diff --check $(git hash-object -t tree /dev/null) HEAD
